DELETE FROM book;
DELETE FROM author;
DELETE FROM book_author_link;
DELETE FROM tag;
DELETE FROM book_tag_link;

DELETE FROM SQLITE_SEQUENCE WHERE name='book';
DELETE FROM SQLITE_SEQUENCE WHERE name='author';
DELETE FROM SQLITE_SEQUENCE WHERE name='book_author_link';
DELETE FROM SQLITE_SEQUENCE WHERE name='tag';
DELETE FROM SQLITE_SEQUENCE WHERE name='book_tag_link';
