DELETE FROM book;
DELETE FROM author;
DELETE FROM book_author_link;
DELETE FROM tag;
DELETE FROM book_tag_link;
DELETE FROM series;
DELETE FROM isbn10;
DELETE FROM isbn13;
DELETE FROM format;

-- reset autoincrement
DELETE FROM SQLITE_SEQUENCE WHERE name='book';
DELETE FROM SQLITE_SEQUENCE WHERE name='author';
DELETE FROM SQLITE_SEQUENCE WHERE name='tag';
DELETE FROM SQLITE_SEQUENCE WHERE name='series';
DELETE FROM SQLITE_SEQUENCE WHERE name='isbn10';
DELETE FROM SQLITE_SEQUENCE WHERE name='isbn13';
DELETE FROM SQLITE_SEQUENCE WHERE name='format';
