root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["templ generate -path ui"]
cmd = "go build -tags \"fts5\" -v -o tmp/dusk ./cmd"
bin = "tmp/dusk"
full_bin = "./tmp/dusk -dsn ./tmp/library.db -dataDir ./tmp/dusk_data"
include_ext = ["go", "templ", "css", "js"]
exclude_dir = ["storage/migrations", ".git", "tmp"]
include_dir = []
exclude_regex = ["_test\\.go", "\\.db", "\\.json", "_templ\\.go"]
exclude_unchanged = true
follow_symlink = true

delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = 500
rerun = false
rerun_delay = 5000

[misc]
clean_on_exit = true
