// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func manualEntryForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form action=\"\" method=\"POST\"><fieldset><label>Title <input type=\"text\" name=\"title\" required></label> <label>Subtitle <input type=\"text\" name=\"subtitle\"></label> <label>Author (semicolon-separated) <input type=\"text\" name=\"author\" required placeholder=\"eg. John Doe; Jane Doe\"></label> <label>ISBN <input type=\"text\" name=\"isbn\"> <small><a href=\"https://www.isbn-13.info/example\">ISBNs</a> must contain 10 or 13 characters, excluding dashes and spaces.</small></label> <label>Identifiers <input type=\"text\" name=\"identifiers\"></label> <label>Tags (comma-separated) <input type=\"text\" name=\"tags\" placeholder=\"eg. science fiction, horror, thriller\"></label></fieldset><fieldset class=\"grid\"><label>Number of Pages <input type=\"number\" name=\"numOfPages\"></label> <label>Rating (out of 10) <input type=\"number\" name=\"rating\"></label></fieldset><fieldset class=\"grid\"><label>Publisher <input type=\"text\" name=\"publisher\"></label> <label>Date Published <input type=\"date\" name=\"datePublished\"></label></fieldset><label>Cover file<div class=\"filedrop-container\"><input type=\"file\" name=\"cover\" accept=\"image/*\" required> <small>Supported file types: jpeg, jpg, png</small></div></label> <details><summary>Optional</summary> <label>Description <textarea name=\"description\"></textarea></label> <label>Notes or Review <textarea name=\"notes\"></textarea></label></details><input type=\"submit\" value=\"Submit\"></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
