// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func manualEntryForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form action=\"\" method=\"POST\"><fieldset><label>Title <input type=\"text\" name=\"title\" required></label> <label>Subtitle <input type=\"text\" name=\"subtitle\"></label> <label>Author (semicolon-separated) <input type=\"text\" name=\"author\" required placeholder=\"eg. John Doe; Jane Doe\"></label> <label>ISBN <input type=\"text\" name=\"isbn\"> <small><a href=\"https://www.isbn-13.info/example\">ISBNs</a> must contain 10 or 13 characters, excluding dashes and spaces.</small></label> <label>Identifiers <input type=\"text\" name=\"identifiers\"></label> <label>Tags (comma-separated) <input type=\"text\" name=\"tags\" placeholder=\"eg. science fiction, horror, thriller\"></label> <label>Series <input type=\"text\" name=\"series\"></label></fieldset><fieldset class=\"grid\"><label>Number of Pages <input type=\"number\" name=\"numOfPages\"></label> <label>Rating (out of 10) <input type=\"number\" name=\"rating\"></label></fieldset><fieldset class=\"grid\"><label>Publisher <input type=\"text\" name=\"publisher\"></label> <label>Date Published <input type=\"date\" name=\"datePublished\"></label></fieldset><label>Cover file<div class=\"filedrop-container\"><input type=\"file\" name=\"cover\" accept=\"image/*\" required> <small>Supported file types: jpeg, jpg, png</small></div></label> <label><input type=\"checkbox\" name=\"another\"> Add another?</label> <input type=\"submit\" value=\"Submit\"> <details><summary>Optional</summary> <label>Description <textarea name=\"description\"></textarea></label> <label>Notes or Review <textarea name=\"notes\"></textarea></label></details></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
